api_platform:
    show_webby: false

    defaults:
        pagination_client_items_per_page: true
        collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header